## Write a program to implement Delta Rule


In [1]:
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
x = np.zeros((3,))


In [3]:
weights = np.zeros((3,))


In [4]:
desired = np.zeros((3,))


In [5]:
actual = np.zeros((3,))


In [6]:
for i in range(0,3):
    x[i] = float(input("Initial Inputs:"))

Initial Inputs:1
Initial Inputs:1
Initial Inputs:1


In [8]:
for i in range(0,3):
    weights[i] = float(input("Initial Weights:"))

Initial Weights:2
Initial Weights:2
Initial Weights:2


In [9]:
for i in range(0,3):
    desired[i] = float(input("Desired Output:"))

Desired Output:3
Desired Output:3
Desired Output:3


In [10]:
a = float(input("Enter Learning Rate:"))


Enter Learning Rate:1


In [11]:
x

array([1., 1., 1.])

In [12]:
weights


array([2., 2., 2.])

In [13]:
desired

array([3., 3., 3.])

In [14]:
a

1.0

In [15]:
actual = x * weights


In [16]:
print("Actual Output:",actual)
print("Desired Output:",desired)

Actual Output: [2. 2. 2.]
Desired Output: [3. 3. 3.]


Delta Rule
==

lr = learning rate 

wnew = wold + lr * (desired[i] - actual[i])


In [17]:
while True:
    if np.array_equal(desired, actual):
        break
    else:
        for i in range(0,3):
            weights[i] = weights[i] + a * (desired[i] - actual[i])
            actual = x * weights

In [18]:
print("Final Output:")
print("Corrected Weights:", weights)
print("Actual Output:",actual)
print("Desired Output:",desired)

Final Output:
Corrected Weights: [3. 3. 3.]
Actual Output: [3. 3. 3.]
Desired Output: [3. 3. 3.]
