In [1]:
import numpy as np
import warnings
warnings.filterwarnings('ignore')


In [2]:
x = np.array([1,1,1,-1,1,-1,1,1,1])


In [3]:
b = 0


In [4]:
#y = output
y = np.array([1,-1])

In [5]:
wtold = np.zeros((9,))
wtnew = np.zeros((9,))

In [6]:
wtnew = wtnew.astype(int)
wtold = wtold.astype(int)

In [7]:
wtnew


array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
wtold

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

Weights update formula
==

wt(new) = wt(old) + xi * y


Bias Update
==

b(new) = b(old) + y


In [9]:
print('First input with target = 1')
for i in range(0,9):
    wtold[i] = wtold[i] + x[i] * y[0]
wtnew = wtold    
b = b + y[0]

First input with target = 1


In [10]:
print('New weights:', wtnew)
print('Bias value:', b)

New weights: [ 1  1  1 -1  1 -1  1  1  1]
Bias value: 1


In [11]:
x2 = np.array([1,1,1,1,-1,1,1,1,1])
x2

array([ 1,  1,  1,  1, -1,  1,  1,  1,  1])

In [12]:
print('First input with target = -1')
for i in range(0,9):
    wtnew[i] = wtold[i] + x2[i] * y[1]
b = b + y[1]

First input with target = -1


In [13]:
print('New weights:', wtnew)
print('Bias value:', b)

New weights: [ 0  0  0 -2  2 -2  0  0  0]
Bias value: 0
